services:
  - type: web
    name: dark-tunnel-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        value: "34808897"
      - key: API_HASH
        sync: false          # set this in the Render dashboard
      - key: BOT_TOKEN
        sync: false          # set this in the Render dashboard
